[[mul]]
T = ["Float64", "ComplexF64"]
I = "Trivial"
dims = [[2, 2, 2], [8, 8, 8], [32, 32, 32], [64, 64, 64], [128, 128, 128]]

[[mul]]
T = ["Float64", "ComplexF64"]
I = "Z2Irrep"
dims = [[2, 2, 2], [8, 8, 8], [32, 32, 32], [64, 64, 64], [128, 128, 128]]
sigmas = [[0.5, 0.5, 0.5]]

[[svd]]
T = ["Float64", "ComplexF64"]
I = "Trivial"
dims = [[2, 2], [8, 8], [32, 32], [64, 64], [128, 128]]

[[svd]]
T = ["Float64", "ComplexF64"]
I = "Z2Irrep"
dims = [[2, 2], [8, 8], [32, 32], [64, 64], [128, 128]]
sigmas = [[0.5, 0.5]]
