[[permute]]
T = ["Float64"]
I = "Trivial"
p = [[[2, 1], []]]
dims = [[7264, 7264], [43408, 1216]]

[[permute]]
T = ["Float64"]
I = "Z2Irrep"
p = [[[2, 1], []]]
dims = [[7264, 7264], [43408, 1216]]
sigmas = [[0.5, 0.5]]
