name: CI

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests:
    name: "Tests"
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/TestGroups.yml@main"
    with:
      fast: "${{ github.event.pull_request.draft == true }}"
      exclude: '["cuda", "amd"]'
      timeout-minutes: 150
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
