name: Compat Check

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Compat bounds check - ${{ matrix.julia-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        downgrade_mode: ['alldeps']
        julia-version: ['1.10', '1']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-downgrade-compat@v2
        with:
          mode: ${{ matrix.downgrade_mode }}
          skip: Random, LinearAlgebra, Test, Combinatorics
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
